### ISSUE TITLE
Cache hash results on the File object

### ISSUE THREAD

**Issue by shevron** [datopian/data.js#109]
In many cases, I see `hash` is called multiple times for the same file. This is wasteful as hashes should not change (assuming the file doesn't change) and are costly to compute. For example, when a file is uploaded via `datapub`, I see `hash` is being called 3 times (once by `datapub`, then by `ckan-client-js` for the `upload` action and then again by `ckan-client-js` for the `verify` action).

IT would be much nicer if the result of `hash` will be cached, per algorithm, on the File object level so it is never calculated twice for the same file / algorithm combo.

**Comment by rufuspollock** [comment]
@shevron 👍  - i imagine that we could add an optional argument e.g. `force` which forces a recompute and otherwise the hash attribute / method caches the result.

**Comment by risenW** [comment]
> In many cases, I see `hash` is called multiple times for the same file. This is wasteful as hashes should not change (assuming the file doesn't change) and are costly to compute. For example, when a file is uploaded via `datapub`, I see `hash` is being called 3 times (once by `datapub`, then by `ckan-client-js` for the `upload` action and then again by `ckan-client-js` for the `verify` action).
> 
> IT would be much nicer if the result of `hash` will be cached, per algorithm, on the File object level so it is never calculated twice for the same file / algorithm combo.

@shevron This issue makes perfect sense, I have some ideas, and I'll look into this, might send a PR later today.

cc @rufuspollock
