### ISSUE TITLE
Add support for datapackage.yml files?

### ISSUE THREAD

**Issue by khughitt** [datopian/data.js#136]
It looks like the library is currently hard-coded to expect json files.

Would it be possible to support `datapackage.yml` files as well?

**Comment by khughitt** [comment]
On second thought; don't waste your time on this now..

Since frictionless-js is primarily targeting the web, and since JSON is the natural way to communicate over the web, I don't think supporting yaml datapackage files (as much as I might prefer it for most purposes), is really all that important.

I'm going to close this for now.

If it turns out to be useful in the future, we can always re-open & consider it then.

**Comment by rufuspollock** [comment]
@khughitt well we use this a lot as a node library. A major use case for yaml is frontmatter in markdown files - using frictionless schema stuff in frontmatter to turn a markdown file into a dataset (or general data literate document). For more see https://portaljs.org/data-literate

**Comment by khughitt** [comment]
@rufuspollock Okay nice! I will take a look. A lot of my earlier efforts were focused around working with metadata files via pipelines & CLI tools, so that framed how I was initially thinking about this.
