### ISSUE TITLE
Data.js should be minimal library and do not use packages like Inquirer

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data.js#20]
Inquirer is the library for prompting users to select options in the command line and it should not be in this lib but in our CLI lib (https://github.com/SBoudrias/Inquirer.js/). 

Note: Inquirer is used in xlsx parser to prompt user to select a sheet when there are more than 1 of sheets. Although it is not needed anymore, we should have it in CLI lib.

## Acceptance criteria

* [x] not using Inquirer

## Tasks

* [x] refactor `/lib/parser/xlsx.js` to remove Inquirer usage - it should process the first sheet by default and have argument to select any other sheets

**Comment by rufuspollock** [comment]
👍
