### ISSUE TITLE
`isDataset` returns false if remote URL for dataset does not include datapackage.json

### ISSUE THREAD

**Issue by zelima** [datopian/data.js#24]
As a datahub user, I want to request info for remote dataset indicating URL to dataset without datapackage.json, as it is more intuitive.

Currently, that is impossible as if URL does not end with datapackage.json we assume it is not a dataset: https://github.com/datahq/data.js/blob/master/lib/index.js#L306

## Acceptance Criteria

* [x] `data info https://datahub.io/core/finance-vix` displays info for dataset
* [ ] isDataset fucntion returns `true` for https://datahub.io/core/finance-vix

## Tasks

* [ ] do analysis
* [ ] tests
* [ ] implementation

**Comment by anuveyatsu** [comment]
We cannot guess if a URL is a dataset if it doesn't consist `datapackage.json` in the end. The only special cases are github and datahub URLs so we're now handling that cases separately.

Info command is already FIXED, therefore, I'm closing this issue as WONTFIX.
