### ISSUE TITLE
Open from Uploaded File

### ISSUE THREAD

**Issue by acouch** [datopian/data.js#49]
When using data.js in the browser it would be useful to be able to open() from using the [File interface](https://developer.mozilla.org/en-US/docs/Web/API/File). Typically files are read with [File Reader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader).

If you need to already parse the file using File Reader or other method then the utility of using data.js is diminished.

I think we could maybe do this by adding a class similar to ``FileRemote`` and ``FileInline`` that reads the uploaded file data.

**Comment by mariorodeghiero** [comment]
@rufuspollock  @kmanaseryan 

Update: 

- Created a draft PR to review https://github.com/datopian/data.js/pull/68

**Comment by kmanaseryan** [comment]
Blocked by #69

**Comment by mariorodeghiero** [comment]
Updates:

- I sent a https://github.com/datopian/data.js/pull/68 to review.

**Comment by kmanaseryan** [comment]
FIXED in #76 and #77
