### ISSUE TITLE
TypeError: data.load is not a function

### ISSUE THREAD

**Issue by starsinmypockets** [datopian/data.js#54]
## Description
The docs refer repeatedly to `dataset.load` but this function appears to have been removed from the library? 

This code:

```
const data = require("data.js")
const conf = data.open('https://datahub.io/starsinmypockets/montreal-kpis')
const fetched = data.load(conf)
console.log(fetched) // <-- uncreachable code
```

Throws the following error:

```
const fetched = data.load(conf)
                     ^
TypeError: data.load is not a function
```

## Action
- [ ] Confirm error
- [ ] Confirm `load` is removed from library
- [ ] Update docs to remove reference to missing function
- [ ] Update docs to clearly demonstrate correct method of loading data resources

**Comment by anuveyatsu** [comment]
@starsinmypockets I don't think we have `data.load` in the README. What we have is `Dataset.load`:

```javascript
const {Dataset} = require('data.js')

const path = '/path/to/directory/' // must have datapackage.json in the directory atm

const dataset = Dataset.load(path)
```

I can see that the README has a mistake when importing..

**Comment by starsinmypockets** [comment]
@anuveyatsu 
Yes, this works:
```
const data = require("data.js")
const url = 'https://datahub.io/starsinmypockets/montreal-kpis'
const resource = data.Dataset.load(url).then(console.log)
```
Maybe this was a misreading of the docs on my part I'll look again.

**Comment by anuveyatsu** [comment]
@starsinmypockets updated the README - https://github.com/datopian/data.js/blob/master/README.md#usage

FIXED in https://github.com/datopian/data.js/commit/0f0d3b0415933842742c7a188f3667ba08e4eeda
