### ISSUE TITLE
Rows method reads first N rows but then continues loading the data

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/data.js#55]
When I call `file.rows({size:100})` it returns me the first 100 rows, however, if I check my browser's network, it is still loading the data.

**Comment by rufuspollock** [comment]
This is actually a hard problem IIRC having done stuff in datapipes. Where is your initial analysis of how you did data streaming etc ?

**Comment by anuveyatsu** [comment]
Analysis are missing at the moment, but here is the code where we do streaming for 'remote' files. Note that this issue is already fixed now by calling `reader.cancel()` (see https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/cancel#targetText=Cancel%20is%20used%20when%20you,is%20not%20readable%20any%20more.)

https://github.com/datopian/data.js/blob/master/src/index.js#L184-L206
