### ISSUE TITLE
Do we need lib folder in the repo?

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/data.js#64]
@rufuspollock I think we should remove `lib` folder from the repo, since it's contains compiled files. However this can be included in `npm publish`

**Comment by rufuspollock** [comment]
@kmanaseryan i don't know ask @anuveyatsu  (btw i'm generally not the person to ask for technical stuff on the js work 😄  - better anu)

**Comment by kmanaseryan** [comment]
> @kmanaseryan i don't know ask @anuveyatsu (btw i'm generally not the person to ask for technical stuff on the js work 😄 - better anu)

ok, sorry 😀

**Comment by anuveyatsu** [comment]
@kmanaseryan i think we need to keep it so that people can install the lib from the github directly. See that entry point of this app is `/lib/...`

**Comment by rufuspollock** [comment]
FIXED / INVALID. We are keeping it.
