### ISSUE TITLE
  Error: unable to locate global object

### ISSUE THREAD

**Issue by mariorodeghiero** [datopian/data.js#80]
I tried to install the last version of the `data.js` in `ckan-client-js` but when I start to run the SDK tests, I receive an error. 
This only happens if I use the **last version** from the `data.js` repository branch master like the code below in SDK package.json. But if I install and use it from the `npm install data.js`, everything works properly.

package.json
` "data.js": "git+https://github.com/datopian/data.js.git"`

Error when I tried to run tests:
```
➜ yarn test:watch
yarn run v1.22.5
$ ava test/*.test.js --verbose --watch

  Uncaught exception in test/upload.test.js

  node_modules/data.js/dist/webpack:/data/node_modules/node-fetch/browser.js:11

  Error: unable to locate global object

  getGlobal (node_modules/data.js/dist/webpack:/data/node_modules/node-fetch/browser.js:11:8)
  Object.call (node_modules/data.js/dist/webpack:/data/node_modules/node-fetch/browser.js:14:14)
  require (node_modules/data.js/dist/webpack:/data/webpack/bootstrap:19:22)
  Object.<anonymous> (node_modules/data.js/dist/webpack:/data/src/index.js:11:15)
  Object.call (node_modules/data.js/dist/datajs.umd.js:10:731280)
  __webpack_require__ (node_modules/data.js/dist/webpack:/data/webpack/bootstrap:19:22)
  node_modules/data.js/dist/webpack:/data/webpack/bootstrap:83:10
  factory (node_modules/data.js/dist/datajs.umd.js:1:1162)
  node_modules/data.js/dist/webpack:/data/webpack/universalModuleDefinition:3:20
  Object.<anonymous> (node_modules/data.js/dist/webpack:/data/webpack/universalModuleDefinition:1:1)

  ✖ test/upload.test.js exited with a non-zero exit code: 1
``

**Comment by anuveyatsu** [comment]
@mariorodeghiero that's expected afaik. You are using `data.js` in Node environment while the latest master is developed for browsers only. You should use it from the release (tag) for Node. We'll have a new release with breaking changes in the future where we will describe how to use it in the Node.

**Comment by rufuspollock** [comment]
@anuveyatsu also in general ckan-client-js should **not** have an explicit dependency on data.js. DataPub should be the one using data.js.

**Comment by rufuspollock** [comment]
INVALID. Don't think anything more here.

Generally i think master should work for node and we have a branch / build for browsers (rather than master being for browser). See #84 for follow up on that.
