### ISSUE TITLE
hash sha-256 is wrong

### ISSUE THREAD

**Issue by mariorodeghiero** [datopian/data.js#86]
As a user I want to run ` const hash = await file.hashSha256()` and return a sha-256 hash. 
The return of the `sample.csv` file in `test/fixtures/sample.csv` should be of the print below. But I am receiving `+fmT1a/ovuOXWfjTkXhWFjIAKB3t+5AHMx0HLxuXzQM=`

**Note:** In the past, I sent a PR to use **CryptoJS** stead of `crypto` to generate a hash for File object in the browser.

Expected:

![Screenshot from 2020-09-15 15-43-12](https://user-images.githubusercontent.com/24671133/93258628-fceed900-f774-11ea-98c6-5488c5e2fa84.png)

cc: @rufuspollock @anuveyatsu

**Comment by kmanaseryan** [comment]
Thanks for opening this issue. @mariorodeghiero maybe CryptoJS was easy to implement, but I think if in Node crypto works then it must to work in the browser. If there is such an issue in the browser then it should exists in the Node. 

I think the encryption is correct as this is how in other file like classes implemented, just the output of encoding is different. In our case we use `base64` encoding. Can you try the same `sample.csv` file to ecrypt with sha256 and use encoding `base64`?

**Comment by kmanaseryan** [comment]
OK, I've used **sample.csv** file here: https://emn178.github.io/online-tools/sha256_checksum.html
It gives me `d9d47b90ac9607c5111ff9a83aa37bc10e058ce6206c00b6626ade091784e098` sha256 hash which is basically has `hex` encoding. 

Just to be clear the **sample.csv** file content is:
```
number,string,boolean
1,two,true
3,four,false
```

Current `hashSha256()` function is the following:
```
async hashSha256() {
    const text = await this.descriptor.text()
    return crypto.createHash('sha256').update(text).digest('base64')
}
```

In the above function if you change the `'base64'` to `'hex'` you will basically get the same output. So the encryption works and encoding as well. I think what you are getting in the online tool is the same hash but with different encoding. 

So closing the issue, but if you can get unexpected result with `'base64'` encoding feel free to reopen this. In your screenshot I can't see if you have used base64 encoding.

**Comment by mariorodeghiero** [comment]
@kmanaseryan ok, I will test with your changes in 3027db3

**Comment by rufuspollock** [comment]
FIXED. We now encode with hex.
