### ISSUE TITLE
Do not include build files in the project

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/data.js#99]
## Acceptance criteria 
- [x] Build files should not be included in the project.
- [x] The content `datajs` folder is moved outside
- [x] Move the FileInterface class outside File script. 
- [x] When I run `yarn build:browser` it builds the files in _dist/browser_ folder
- [x] When I run `yarn build:node` it builds the files in _dist/node_ folder
- [x] The main in the package.json is mount to "dist/node/index.js"
- [x] README is updated accordingly

**Comment by risenW** [comment]
@kmanaseryan I added the FileInterface (num 3) update we talked about yesterday to the acceptance criteria of this issue.

**Comment by risenW** [comment]
@kmanaseryan See fix here #101
